### ISSUE TITLE
No LICENSE, can I copy and modify code?

### ISSUE THREAD

**Issue by dopdahl16** [bclemens6/hedges-for-gardens#1]
Hello @bclemens6, 
First of all, I want to say that I'm a big fan! I frequent FanGraphs and I love your writing. I'm currently working on a baseball simulation project that's similar to the script in this repo in function, but a little more tweaked and tailored to my specific needs. Can I use your code in that project? I'm using it non-commercially to help the baseball coach at my college process data and make managerial decisions this fall. I would fork the repo directly, but there's already a lot of background work and already has its own repo with history that I don't want to give up. I'd make sure to mark what parts of the code are yours directly and what parts are inspired by your code and I'd make sure that your copyright is honored. Let me know what you think. Thank you!
From the Lion's Den,
Daniel Opdahl

**Comment by bclemens6** [comment]
No copyright issues at all. Please feel free to take whatever you'd like. I
posted it in the hope that it would be useful for others to take and
modify.

**Comment by dopdahl16** [comment]
Fantastic! Thanks so much!
